AutoskolaWeb/AutoskolaWeb/Controllers/AnswerController.cs
using AutoskolaWeb.DAL;
using AutoskolaWeb.Model;
using AutoskolaWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutoskolaWeb.Controllers
{ 
    [Authorize]
    public class AnswerController : ControllerBase
    {
        [Authorize(Roles = "Admin")]
        public ActionResult Index() 
        {
            var model = AnswerRepository.All.ToList();
            return View(model);
        }
        
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult IndexAjax(AnswerFilterModel filter)
        {
            var answerQuery = AnswerRepository.All;

            if (!string.IsNullOrWhiteSpace(filter.AnswerText))
                answerQuery = answerQuery.Where(p => p.AnswerText.Contains(filter.AnswerText));

            var model = answerQuery.ToList();

            return PartialView("_IndexTable", model);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id)
        {
            var model = AnswerRepository.Find(id);

            return View(model);
        }

       [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            FillDropdownValues();
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(Answer model)
        {
            if(ModelState.IsValid)
            {
                AnswerRepository.Insert(model);
                AnswerRepository.Save();
            }

            FillDropdownValues();
            return View(model);
        }

       [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            FillDropdownValues();

            var model = AnswerRepository.Find(id);

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ActionName("Edit")]
        public ActionResult EditPost(Answer formModel)
        {
            if (ModelState.IsValid)
            {
                var modelDb = AnswerRepository.Find(formModel.ID);
                if(this.TryUpdateModel(modelDb))
                {
                    AnswerRepository.Update(modelDb);
                    AnswerRepository.Save();

                    return RedirectToAction("Index");
                }
            }

            FillDropdownValues();
            return View(formModel);
        }

       [Authorize(Roles = "Admin")]
        public JsonResult Delete(int id)
        {
            QuizRepository.Delete(id);
            QuizRepository.Save();

            return new JsonResult() { Data = "OK", JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        private void FillDropdownValues()
        {
            var possibleAnswers = AnswerRepository.All.ToList();

            var selectItems = new List<SelectListItem>();

            var listItem = new SelectListItem(); 
            listItem.Text = "- odaberite -";
            listItem.Value = "";
            selectItems.Add(listItem);

            foreach (var answer in possibleAnswers)
            {
                listItem = new SelectListItem();
                listItem.Text = answer.AnswerText;
                listItem.Value = answer.ID.ToString();
                listItem.Selected = false;
                selectItems.Add(listItem);
            }
            ViewBag.PossibleAnswers = selectItems;
        }
    }
    }

AutoskolaWeb/AutoskolaWeb/Controllers/QuestionController.cs
using AutoskolaWeb.DAL;
using AutoskolaWeb.Model;
using AutoskolaWeb.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace AutoskolaWeb.Controllers
{
    [Authorize]
    public class QuestionController : ControllerBase
    {
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var model = QuestionRepository.All.ToList(); 

            return View(model);
        }
        
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult IndexAjax(QuestionFilterModels filter)
        {
            var questionQuery = QuestionRepository.All;

            if (!string.IsNullOrWhiteSpace(filter.QuestionText))
                questionQuery = questionQuery.Where(p => p.QuestionText.Contains(filter.QuestionText));

            var model = questionQuery.ToList();

            return PartialView("_IndexTable", model);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id)
        {
            var model = QuestionRepository.Find(id);

            return View(model);
        }


        [Authorize(Roles = "Admin")]
        public ActionResult AddAnswer(int id)
        {
            FillDropdownValues();
            var model = QuestionRepository.Find(id);
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ActionName("AddAnswer")]
        public ActionResult AddAnswerPost(Question formModel, int Answer)
        {
            if (ModelState.IsValid)
            {
                var modelDb = QuestionRepository.Find(formModel.ID);
                var modelAnswer = AnswerRepository.Find(Answer);
                modelDb.Answers.Add(modelAnswer);
                if (this.TryUpdateModel(modelDb))
                {
                    QuestionRepository.Update(modelDb);
                    QuestionRepository.Save();

                    //return RedirectToAction("Index");
                }

            }
            FillDropdownValues();
            return View(formModel);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult AddImage(int id) {
        
            var model = QuestionRepository.Find(id);
            return View(model);
        
        
        }

        
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ActionName("AddImage")]
        public ActionResult AddImagePost(HttpPostedFileBase file, int id)
        {
            if (file != null && file.ContentLength > 0)
            {
                var fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/App_Data/images"), fileName);
                file.SaveAs(path);


                if (ModelState.IsValid)
                {
                    var modelDb = QuestionRepository.Find(id);

                    modelDb.Image = new byte[file.ContentLength];
                    file.InputStream.Read(modelDb.Image, 0, file.ContentLength);

                    if (this.TryUpdateModel(modelDb))
                    {
                        QuestionRepository.Update(modelDb);
                        QuestionRepository.Save();

                        return RedirectToAction("Index");
                    }

                }
            }
            return View();
        }
        [HttpGet]
        public FileContentResult getImg(int id)
        {
            byte[] byteArray = QuestionRepository.Find(id).Image;
            return byteArray != null
                ? new FileContentResult(byteArray, "image/jpeg")
                : null;
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            FillDropdownValues();
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(Question model)
        {
            if(ModelState.IsValid)
            {
                QuestionRepository.Insert(model);
                QuestionRepository.Save();
                //return RedirectToAction("Index");
            }

            FillDropdownValues();
            return View(model);
        }

       [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            FillDropdownValues();

            var model = QuestionRepository.Find(id);

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ActionName("Edit")]
        public ActionResult EditPost(Question formModel)
        {
            if (ModelState.IsValid)
            {
                var modelDb = QuestionRepository.Find(formModel.ID);
                
                if(this.TryUpdateModel(modelDb))
                {
                    QuestionRepository.Update(modelDb);
                    QuestionRepository.Save();

                    return RedirectToAction("Index");
                }
            }

            FillDropdownValues();
            return View(formModel);
        }

       [Authorize(Roles = "Admin")]
        public JsonResult Delete(int id)
        {
            QuestionRepository.Delete(id);
            QuestionRepository.Save();

            return new JsonResult() { Data = "OK", JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        //Brisanje odgovora iz kviza
        [Authorize(Roles = "Admin")]
        public JsonResult DeleteAnswer(int id, int questionId)
        {
            var modelAnswer = AnswerRepository.Find(id);
            var modelQuestion = QuestionRepository.Find(questionId);
            modelQuestion.Answers.Remove(modelAnswer);
            QuestionRepository.Update(modelQuestion);
            QuestionRepository.Save();

            return new JsonResult() { Data = "OK", JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        private void FillDropdownValues()
        {
            var possibleAnswers = AnswerRepository.All.ToList();

            var selectItems = new List<SelectListItem>();

            var listItem = new SelectListItem(); 
            listItem.Text = "- odaberite -";
            listItem.Value = "";
            selectItems.Add(listItem);

            foreach (var answer in possibleAnswers)
            {
                listItem = new SelectListItem();
                listItem.Text = answer.AnswerText;
                listItem.Value = answer.ID.ToString();
                listItem.Selected = false;
                selectItems.Add(listItem);
            }
            ViewBag.PossibleAnswers = selectItems;
        }
    }
    }

AutoskolaWeb/AutoskolaWeb/Views/Question/AddAnswer.cshtml
@model AutoskolaWeb.Model.Question
@{
    ViewBag.Title = "Add answer";
}

<h2>Add answer</h2>

@using (Html.BeginForm())
{
    <text>
        @Html.Partial("_AddAnswer")
        @Html.HiddenFor(p => p.ID)
    </text>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AutoskolaWeb/AutoskolaWeb/Views/Question/AddImage.cshtml
@model AutoskolaWeb.Model.Question
@{
    ViewBag.Title = "Add image for question";
}

<h2>Add image for question</h2>


    <text>
        @Html.Partial("_AddImage")
        @Html.HiddenFor(p => p.ID)
    </text>



<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AutoskolaWeb/AutoskolaWeb/Views/Question/Create.cshtml
@model AutoskolaWeb.Model.Question

@{
    ViewBag.Title = "New question";
}

<h2>New question</h2>

@using (Html.BeginForm())
{
    <text>
        @Html.Partial("_CreateOrEdit")
    </text>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AutoskolaWeb/AutoskolaWeb/Views/Question/Details.cshtml
@model AutoskolaWeb.Model.Question

@{
    ViewBag.Title = "Question details";
}

<h2>Question details</h2>

@if (Model == null)
{
    <div class="alert alert-danger" role="alert">Ne postoji odabrano pitanje!</div>
}
else
{
    <table class="table table-condensed">
        <tbody>
            <tr>
                <th>ID</th>
                <td>@Model.ID</td>
            </tr>
            <tr>
                <th>Tekst pitanja</th>
                <td>@Model.QuestionText</td>
            </tr>
            <tr>
                <th>Točan odgovor</th>
                <td>@Model.CorrectAnswer</td>
            </tr>
            <tr>
                <td colspan="2">@Html.ActionLink("Uredi", "Edit", new { id = Model.ID })</td>
            </tr>
        </tbody>
    </table>
}

AutoskolaWeb/AutoskolaWeb/Views/Question/Edit.cshtml
@model AutoskolaWeb.Model.Question

@{
    ViewBag.Title = "Edit question";
}

<h2>Edit question</h2>

@using (Html.BeginForm())
{

    <text>
        @Html.Partial("_CreateOrEdit")
        @Html.HiddenFor(p => p.ID)
    </text>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@using (Html.BeginForm())
{
    <text>
        @Html.Partial("_AnswerTable", Model.Answers.ToList())
        @Html.HiddenFor(p => p.ID, new { id = "QuestionId" })

    </text>
}

AutoskolaWeb/AutoskolaWeb/Views/Question/Index.cshtml
@model List<AutoskolaWeb.Model.Question>

@{
    ViewBag.Title = "Index";
}

<h2>Questions</h2>

@Html.Partial("_QuestionFilter", new AutoskolaWeb.Models.QuestionFilterModels())

@Html.Partial("_IndexTable", Model)

@section scripts{

    <style type="text/css">
        table.table tr.bold {
            font-weight: bold;
        }
    </style>
    <script type="text/javascript">
        $(function () {
            $(".quiz-filter-form .submit-button").on("click", function () {
                $.ajax({
                    url: '@Url.Action("IndexAjax")',
                    method: "POST",
                    data: $(this).closest('form').serialize(),
                    success: function(data){
                        $("#tbl-quizzes").replaceWith(data);
                    }

                });
            });
        });

        function deleteRow(link) {
            var tr = $(link).closest('tr');
            $.ajax({
                url: '@Url.Action("Delete")',
                method: "GET",
                data: { 'id': tr.attr('quizId')},
                success: function (data) {
                    if (data == "OK")
                        tr.remove();
                    else
                        alert('Brisanje neuspjelo!');
                }

            });
        }
        

    </script>

}

AutoskolaWeb/AutoskolaWeb/Views/Question/_AddAnswer.cshtml
@model AutoskolaWeb.Model.Question
<div class="form-group">
    @Html.LabelFor(model => model.Answers, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DropDownList("Answer", (IEnumerable<SelectListItem>)ViewBag.PossibleAnswers, new { @class = "form-control" })
    </div>
</div>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Spremi" class="btn btn-default" />
    </div>
</div>

AutoskolaWeb/AutoskolaWeb/Views/Question/_AddImage.cshtml
@model AutoskolaWeb.Model.Question

@using(Html.BeginForm("AddImage", "Question", FormMethod.Post, new {id="form", enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(x => x.ID)
    <input type="file" name="file" id="file" />
    <input type="submit" value="submit" name="submit"  id="submit"/>
    

}
   @Html.Partial("_GetImage")
   

AutoskolaWeb/AutoskolaWeb/Views/Question/_AnswerTable.cshtml
@model List<AutoskolaWeb.Model.Answer>

<table id="tbl-quizzes" class="table table-condensed table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Answer</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var answer in Model)
        {

            <tr answerid="@answer.ID">
                <td>@answer.ID</td>
                <td>@answer.AnswerText</td>
                <td><a href="javascript:void(0)" onclick="deleteRowAnswer(this);">Delete</a></td>
            </tr>


        }

    </tbody>
</table>
<script type="text/javascript">
    $(function () {
        $(".quiz-filter-form .submit-button").on("click", function () {
            $.ajax({
                url: '@Url.Action("IndexAjax")',
                method: "POST",
                data: $(this).closest('form').serialize(),
                success: function (data) {
                    $("#tbl-quizzes").replaceWith(data);
                }

            });
        });
    });


    function deleteRowAnswer(link) {
        var tr = $(link).closest('tr');
        var id= $('#QuestionId').val();
        $.ajax({
            url: '@Url.Action("DeleteAnswer")',
            method: "GET",
            data: {
                'id': tr.attr('answerid'),
                'questionId': id
            },
                success: function (data) {
                if (data == "OK")
                    tr.remove();
                else
                    alert('Brisanje neuspjelo!');
            }

        });
    }

</script>

AutoskolaWeb/AutoskolaWeb/Views/Question/_CreateOrEdit.cshtml
@model AutoskolaWeb.Model.Question

<div class="form-horizontal">

    <div class="form-group">
        @Html.LabelFor(model => model.QuestionText, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.QuestionText, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.CorrectAnswer, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CorrectAnswer, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Spremi" class="btn btn-default" />
        </div>
    </div>
</div>

AutoskolaWeb/AutoskolaWeb/Views/Question/_GetImage.cshtml
@model AutoskolaWeb.Model.Question

<img src="@Url.Action("getImg", "Question", new { id = @Model.ID })" alt="Question Image" />

AutoskolaWeb/AutoskolaWeb/Views/Question/_IndexTable.cshtml
@model List<AutoskolaWeb.Model.Question>

<table id="tbl-quizzes" class="table table-condensed table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Question</th>
            <th>Correct answer</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var question in Model)
        {
            <tr quizid="@question.ID">
                <td>@question.ID</td>
                <td>@question.QuestionText</td>
                <td>@question.CorrectAnswer</td>
                <td>@Html.ActionLink("Details", "Details", new { id = question.ID })</td>
                <td>@Html.ActionLink("Edit", "Edit", new { id = question.ID })</td>
                <td>@Html.ActionLink("Add answer", "AddAnswer", new { id = question.ID })</td>
                <td>@Html.ActionLink("Add image for question", "AddImage", new { id = question.ID })</td>
                <td><a href="javascript:void(0)" onclick="deleteRow(this);">Delete</a></td>
            </tr>
        }

    </tbody>
</table>

AutoskolaWeb/AutoskolaWeb/Views/Question/_QuestionFilter.cshtml
@model AutoskolaWeb.Models.QuestionFilterModels

<form action="@Url.Action("AdvancedSearch")" method="post" class="quiz-filter-form form-horizontal" role="form">
    <div class="form-group">
        @Html.TextBoxFor(p => p.QuestionText, new { @class = "form-control", placeholder = "Search" })
    </div>
    <div class="form-group">
        <div class="col-md-12">
            <button type="button" class="btn btn-default submit-button">Search</button>
        </div>
    </div>

</form>